### ISSUE TITLE
Can sx1278 433m works

### ISSUE THREAD

**Issue by DusKing1** [RavenLRS/raven#10]
I bought an sx1278 works on 433m, but I don't know whether it can be supported by software.

Some ideas? I hate to waste my money:-(

**Comment by fiam** [comment]
Which boards did you buy? I’m mainly using boards with SX1278 on 433Mhz, so that shouldn’t be a problem.

**Comment by DusKing1** [comment]
thanks for your answer but maybe I ask this question in wrong reposity.

It's my friend's problem and it should be asked in another reposity.

sry for wasting your time @fiam
