### ISSUE TITLE
RHF76-052 or RAK811 as RX?

### ISSUE THREAD

**Issue by michal-konopinski** [RavenLRS/raven#42]
Both have sx1276 and stm32, first STM32L052C8, second STM32L151CB.

**Comment by DieHertz** [comment]
Have you traced their schematic and written the code?

**Comment by michal-konopinski** [comment]
I'm just asking if it's worth trying ;)

**Comment by michal-konopinski** [comment]
There's no need for tracing schematic, the documentation is freely available:
http://risinghf.com/#/product-details?product_id=5&lang=en
https://github.com/RAKWireless/RAK811

**Comment by fiam** [comment]
There are no plans to support 3rd party STM32 boards, except for maybe the R9 receivers from FrSky since those have a form factor convenient for radio control applications.
