### ISSUE TITLE
Video test 

### ISSUE THREAD

**Issue by mikerc2017** [RavenLRS/raven#6]
hi developer 

Can you show me a video test it work or a flight ? i real impressive with your work .  

In schematic modul TX , i not see pin connect to pin number one Taranis ,??

**Comment by mikerc2017** [comment]
@fiam  please answer me

**Comment by pdwdw** [comment]
http://www.hobbyeyes.com/index/Video/detail?vid=19db2ee3-ff01-7d4c-d7ab-48bd81a4432a&vd=0

**Comment by pdwdw** [comment]
> 嗨开发者
> 
> 你能告诉我它的视频测试吗？我对你的工作印象深刻。
> 
> 在原理图模块TX中，我没有看到引脚连接到引脚编号Taranis，??

http://www.hobbyeyes.com/index/Video/detail?vid=19db2ee3-ff01-7d4c-d7ab-48bd81a4432a&vd=0

**Comment by mikerc2017** [comment]
hi @pdwdw 
what is your mail ? i need to help about this project. I can not register web China .
please .Thanks

**Comment by DusKing1** [comment]
@mikerc2017 I can help you. 1483569698@qq.com
